<template>
  <div :class="`loading-spinner${$props.size && ` loading-spinner--${$props.size}`}`">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      class="loading-spinner__img"
      width="200px"
      height="200px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <g transform="translate(50 42)">
        <g transform="scale(0.8)">
          <g transform="translate(-50 -50)">
            <polygon fill="#93dbe9" points="72.5 50 50 11 27.5 50 50 50">
              <animateTransform
                attributeName="transform"
                type="rotate"
                repeatCount="indefinite"
                dur="2.4390243902439024s"
                values="0 50 38.5;360 50 38.5"
                keyTimes="0;1"
              ></animateTransform>
            </polygon>
            <polygon fill="#689cc5" points="5 89 50 89 27.5 50">
              <animateTransform
                attributeName="transform"
                type="rotate"
                repeatCount="indefinite"
                dur="2.4390243902439024s"
                values="0 27.5 77.5;360 27.5 77.5"
                keyTimes="0;1"
              ></animateTransform>
            </polygon>
            <polygon fill="#5e6fa3" points="72.5 50 50 89 95 89">
              <animateTransform
                attributeName="transform"
                type="rotate"
                repeatCount="indefinite"
                dur="2.4390243902439024s"
                values="0 72.5 77.5;360 72 77.5"
                keyTimes="0;1"
              ></animateTransform>
            </polygon>
          </g>
        </g>
      </g>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
  </div>
</template>
<script setup lang="ts">
defineProps({
  size: {
    type: String,
    default: "",
  },
});
</script>
<style lang="scss" scoped>
.loading-spinner {
  background-color: transparent;
  height: 100%;
  // overflow: hidden;
  width: 100%;

  &--full-screen {
    background-color: rgb(18 52 86 / 80%);
    bottom: 0;
    left: 0;
    position: absolute;
    right: 0;
    top: 0;
    z-index: 500;
  }

  &__img {
    background: none;
    display: block;
    height: 100%;
    margin: auto;
    shape-rendering: auto;
    width: 100%;
  }
}
</style>
